### ISSUE TITLE
Letter Tracing instead of frame?

### ISSUE THREAD

**Issue by jantoney** [ksjh/LEDneon#1]
Hey - First of all thank you for this repo! It's truly amazing. I'm a big fan of BigClive as well.

I'm trying to do a NEON sign with letters and was wondering if there was a chance you could do a script to trace a font, instead of framing it and going around the edges.

Super bad example, but I'm hoping you get what I'm trying to say from this image example. Random image search result
[https://cdn.notonthehighstreet.com/fs/ff/45/6464-6716-43dc-8036-b1d8aef041d3/original_sweet-neon-wall-sign.jpg](https://cdn.notonthehighstreet.com/fs/ff/45/6464-6716-43dc-8036-b1d8aef041d3/original_sweet-neon-wall-sign.jpg)

Thanks in advance!

PS: I know this isn't an issue, but discussions doesn't seem to be enabled for this repo - so sorry for the 'issue'.

**Comment by ksjh** [comment]
I was also wondering how we could do this. There are two fundamental problems: Normal fonts just define the outline of glyphs (letters), but we would need the midpoints. I see no obvious way in OpenSCAD to generate these midpoints. The other problem is that the rounding method I used does not work in this case, it needs an area in 2D first.

But I added another module that allows to trace lines. So you need to draw the text you want to trace as lines of neglectable width (e.g. in Inkscape) and use my new module to generate the frame. Please make sure that there are no pointed angles between any lines. Either round them off first (convert them to arcs of suitable size) or make sure that the angles are more or less 90 degrees, so that you can butt two (or three) pieces of LED neon together at the crossing point.

**Comment by ksjh** [comment]
By the way, I also enabled discussions of this repo. Thank you for all your suggestions.
